# Author: Matt Watts
# Date: 12 Dec 2014
# Purpose: Activity4a4b web app ui.R

require(shiny)

shinyUI(pageWithSidebar(

	headerPanel("MConsBiol Activities 4a and 4b"),
	
	sidebarPanel(
        radioButtons("map", "Map to display:",
                     list("Best solutions difference map (1 vs 2)" = "bestmap",
                          "Best solution Acquisition cost (1)" = "bestacq",
                          "Best solution Management cost (2)" = "bestdist",
                          "Best solution Area cost (3)" = "bestarea",
                          "Selection frequencies difference map (1 vs 2)" = "ssolnNmap",
                          "Selection frequency Acquisition cost (1)" = "ssolnacq",
                          "Selection frequency Management cost (2)" = "ssolndist",
                          "Selection frequency Area cost (3)" = "ssolnarea")),

        conditionalPanel(condition = "input.map == 'bestmap' | input.map == 'runMmap'",
                         HTML("<img src='http://marxan.net/images/green.png' /></a>"),
                         HTML("Acquisition"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue.png' /></a>"),
                         HTML("Management"),
                         br(),
                         HTML("<img src='http://marxan.net/images/turquoise.png' /></a>"),
                         HTML("Both")
                        ),
        conditionalPanel(condition = "input.map == 'bestacq'",
                         HTML("<img src='http://marxan.net/images/green.png' /></a>"),
                         HTML("Acquisition")
                        ),
        conditionalPanel(condition = "input.map == 'bestdist'",
                         HTML("<img src='http://marxan.net/images/blue.png' /></a>"),
                         HTML("Management")
                        ),
        conditionalPanel(condition = "input.map == 'bestarea'",
                         HTML("<img src='http://marxan.net/images/red.png' /></a>"),
                         HTML("Area")
                        ),

        conditionalPanel(condition = "input.map == 'ssolnNmap'",
                         HTML("<img src='http://marxan.net/images/turquoise.png' /></a>"),
                         HTML("Acquisition = Management"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green10.png' /></a>"),
                         HTML("10 Acquisition is higher"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green9.png' /></a>"),
                         HTML("9"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green8.png' /></a>"),
                         HTML("8"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green7.png' /></a>"),
                         HTML("7"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green6.png' /></a>"),
                         HTML("6"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green5.png' /></a>"),
                         HTML("5"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green4.png' /></a>"),
                         HTML("4"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green3.png' /></a>"),
                         HTML("3"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green2.png' /></a>"),
                         HTML("2"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green1.png' /></a>"),
                         HTML("1"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue10.png' /></a>"),
                         HTML("10 Management is higher"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue9.png' /></a>"),
                         HTML("9"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue8.png' /></a>"),
                         HTML("8"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue7.png' /></a>"),
                         HTML("7"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue6.png' /></a>"),
                         HTML("6"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue5.png' /></a>"),
                         HTML("5"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue4.png' /></a>"),
                         HTML("4"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue3.png' /></a>"),
                         HTML("3"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue2.png' /></a>"),
                         HTML("2"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue1.png' /></a>"),
                         HTML("1")
                       ),
        conditionalPanel(condition = "input.map == 'ssolnacq'",
                         HTML("Acquisition"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green10.png' /></a>"),
                         HTML("10"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green9.png' /></a>"),
                         HTML("9"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green8.png' /></a>"),
                         HTML("8"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green7.png' /></a>"),
                         HTML("7"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green6.png' /></a>"),
                         HTML("6"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green5.png' /></a>"),
                         HTML("5"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green4.png' /></a>"),
                         HTML("4"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green3.png' /></a>"),
                         HTML("3"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green2.png' /></a>"),
                         HTML("2"),
                         br(),
                         HTML("<img src='http://marxan.net/images/green1.png' /></a>"),
                         HTML("1")
                        ),
        conditionalPanel(condition = "input.map == 'ssolndist'",
                         HTML("Management"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue10.png' /></a>"),
                         HTML("10"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue9.png' /></a>"),
                         HTML("9"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue8.png' /></a>"),
                         HTML("8"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue7.png' /></a>"),
                         HTML("7"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue6.png' /></a>"),
                         HTML("6"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue5.png' /></a>"),
                         HTML("5"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue4.png' /></a>"),
                         HTML("4"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue3.png' /></a>"),
                         HTML("3"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue2.png' /></a>"),
                         HTML("2"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue1.png' /></a>"),
                         HTML("1")
                        ),
        conditionalPanel(condition = "input.map == 'ssolnarea'",
                         HTML("Area"),
                         br(),
                         HTML("<img src='http://marxan.net/images/red10.png' /></a>"),
                         HTML("10"),
                         br(),
                         HTML("<img src='http://marxan.net/images/red9.png' /></a>"),
                         HTML("9"),
                         br(),
                         HTML("<img src='http://marxan.net/images/red8.png' /></a>"),
                         HTML("8"),
                         br(),
                         HTML("<img src='http://marxan.net/images/red7.png' /></a>"),
                         HTML("7"),
                         br(),
                         HTML("<img src='http://marxan.net/images/red6.png' /></a>"),
                         HTML("6"),
                         br(),
                         HTML("<img src='http://marxan.net/images/red5.png' /></a>"),
                         HTML("5"),
                         br(),
                         HTML("<img src='http://marxan.net/images/red4.png' /></a>"),
                         HTML("4"),
                         br(),
                         HTML("<img src='http://marxan.net/images/red3.png' /></a>"),
                         HTML("3"),
                         br(),
                         HTML("<img src='http://marxan.net/images/red2.png' /></a>"),
                         HTML("2"),
                         br(),
                         HTML("<img src='http://marxan.net/images/red1.png' /></a>"),
                         HTML("1")
                        ),

        conditionalPanel(condition = "input.prop == -1",
                         sliderInput("m", "Solution M:",
                                     value = 1,
                                     min = 1,
                                     max = iNUMREPS, step = 1),
                         numericInput("testinput", "Test Input", 0))
        ),

	mainPanel(
	    plotOutput('marxanmap')
	)
))
